name: macOS Build and Package

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Package macOS App
    runs-on: macos-14 # Usar macOS 14 (Sonoma) que tiene Xcode 15.x

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para obtener todos los tags para versionado
        
      - name: Show Environment Info
        run: |
          echo "macOS Version:"
          sw_vers
          echo "\nXcode Version:"
          xcodebuild -version
          echo "\nSwift Version:"
          swift --version
        
      - name: Make Build Script Executable
        run: chmod +x ./build_release.sh
        
      - name: Run Build Script
        run: ./build_release.sh
        
      - name: Find DMG File
        id: find-dmg
        run: |
          DMG_FILE=$(find ./artifacts -name "*.dmg" | head -1)
          if [ -z "$DMG_FILE" ]; then
            echo "::error::No DMG file found"
            exit 1
          fi
          echo "DMG_FILE=$DMG_FILE" >> $GITHUB_OUTPUT
          echo "DMG_NAME=$(basename "$DMG_FILE")" >> $GITHUB_OUTPUT
            
      - name: Upload DMG as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DevIconGenerator-macOS
          path: ${{ steps.find-dmg.outputs.DMG_FILE }}
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find-dmg.outputs.DMG_FILE }}
          name: DevIconGenerator ${{ github.ref_name }}
          body: |
            # DevIconGenerator ${{ github.ref_name }}
            
            Generador de iconos para aplicaciones iOS, iPadOS, macOS y watchOS.
            
            ## Instalación
            
            Descarga el archivo DMG y arrastra la aplicación a tu carpeta de Aplicaciones.
            
            ## Cambios en esta versión
            
            * Mejoras en la interfaz de usuario
            * Corrección de errores
            * Optimización de rendimiento
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
